# Generated by Django 4.2.2 on 2023-06-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
