# Generated by Django 4.2.2 on 2023-06-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_adminreg_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminreg',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminreg',
            name='user_permissions',
        ),
    ]
