# Generated by Django 4.2.2 on 2023-06-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_adminlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='username',
            new_name='email',
        ),
    ]
