# Generated by Django 4.2.2 on 2023-06-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_subjectdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectdetails',
            old_name='subject',
            new_name='sub_name',
        ),
    ]
