# Generated by Django 4.2.2 on 2023-06-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=2)),
            ],
        ),
    ]
